### ISSUE TITLE
It should be more obvious when a proposal is withdrawn.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#199]
<img width="1280" alt="screen shot 2015-12-10 at 12 07 12 pm" src="https://cloud.githubusercontent.com/assets/4720348/11723950/ae7e8d74-9f36-11e5-96cf-daecea6d07f0.png">

The blue banner doesn't stand out enough imo.

**Comment by malrase** [comment]
It could be in a different colour, _or_ maybe increase the size of the banner? That's currently our standard banner for signing in, etc.

**Comment by rakeshak** [comment]
Animating the appearance of the banner would make it more obvious. For example, The banner can slide down to position as if it's coming from underneath the header and disappear after a few seconds. Or, we could even move the banner atop the header (as if it's sliding from the top edge of the viewport). As usual any animation shall last from 0.2 to 0.5 seconds and not more than that.

**Comment by HamptonMakes** [comment]
Now that we have a "confirm" dialog that comes up when you withdraw, I don't think this is as much of an issue. However, I would say that the proposal itself should be more clear. In my opinion, the voting bar should turn grey and a small note should go under the main word indicating that it's been withdrawn.

**Comment by rakeshak** [comment]
The only time somebody would see a withdrawn proposal is immediately after the withdrawal, right? If so, the banner should suffice (we should probably make the banner red). In addition we can fade the content of the proposal (here I've changed the opacity to 0.25):
![withdrawn proposal](https://cloud.githubusercontent.com/assets/14918841/11891644/95b00376-a586-11e5-935a-af5150965a03.jpg)
Instead of asking for confirmation before withdrawal we should probably withdraw immediately and provide an option to undo or withdraw after a few seconds again providing an option to undo.

**Comment by HamptonMakes** [comment]
Withdrawn proposals stay part of word history forever... and are listed in
our main proposals list.
